export const BUG_LIST_REQUEST = 'BUG_LIST_REQUEST'
export const BUG_LIST_SUCCESS = 'BUG_LIST_SUCCESS'
export const BUG_LIST_FAIL = 'BUG_LIST_FAIL'

export const BUG_CREATE_REQUEST = 'BUG_CREATE_REQUEST'
export const BUG_CREATE_SUCCESS = 'BUG_CREATE_SUCCESS'
export const BUG_CREATE_FAIL = 'BUG_CREATE_FAIL'
export const BUG_CREATE_RESET = 'BUG_CREATE_RESET'