export const LANGUAGE_LIST_REQUEST = 'LANGUAGE_LIST_REQUEST'
export const LANGUAGE_LIST_SUCCESS = 'LANGUAGE_LIST_SUCCESS'
export const LANGUAGE_LIST_FAIL = 'LANGUAGE_LIST_FAIL'

export const LANGUAGE_DETAIL_REQUEST = 'LANGUAGE_DETAIL_REQUEST'
export const LANGUAGE_DETAIL_SUCCESS = 'LANGUAGE_DETAIL_SUCCESS'
export const LANGUAGE_DETAIL_FAIL = 'LANGUAGE_DETAIL_FAIL'