export const LANGUAGE_LIST_REQUEST = 'LANGUAGE_LIST_REQUEST'
export const LANGUAGE_LIST_SUCCESS = 'LANGUAGE_LIST_SUCCESS'
export const LANGUAGE_LIST_FAIL = 'LANGUAGE_LIST_FAIL'

export const LANGUAGE_DETAIL_REQUEST = 'LANGUAGE_DETAIL_REQUEST'
export const LANGUAGE_DETAIL_SUCCESS = 'LANGUAGE_DETAIL_SUCCESS'
export const LANGUAGE_DETAIL_FAIL = 'LANGUAGE_DETAIL_FAIL'

export const LANGUAGE_CREATE_REQUEST = 'LANGUAGE_CREATE_REQUEST'
export const LANGUAGE_CREATE_SUCCESS = 'LANGUAGE_CREATE_SUCCESS'
export const LANGUAGE_CREATE_FAIL = 'LANGUAGE_CREATE_FAIL'
export const LANGUAGE_CREATE_RESET = 'LANGUAGE_CREATE_RESET'