export const LANGUAGE_LIST_REQUEST = 'LANGUAGE_LIST_REQUEST'
export const LANGUAGE_LIST_SUCCESS = 'LANGUAGE_LIST_SUCCESS'
export const LANGUAGE_LIST_FAIL = 'LANGUAGE_LIST_FAIL'

export const LANGUAGE_DETAIL_REQUEST = 'LANGUAGE_DETAIL_REQUEST'
export const LANGUAGE_DETAIL_SUCCESS = 'LANGUAGE_DETAIL_SUCCESS'
export const LANGUAGE_DETAIL_FAIL = 'LANGUAGE_DETAIL_FAIL'

export const LANGUAGE_CREATE_REQUEST = 'LANGUAGE_CREATE_REQUEST'
export const LANGUAGE_CREATE_SUCCESS = 'LANGUAGE_CREATE_SUCCESS'
export const LANGUAGE_CREATE_FAIL = 'LANGUAGE_CREATE_FAIL'
export const LANGUAGE_CREATE_RESET = 'LANGUAGE_CREATE_RESET'

export const LANGUAGE_UPDATE_REQUEST = 'LANGUAGE_UPDATE_REQUEST'
export const LANGUAGE_UPDATE_SUCCESS = 'LANGUAGE_UPDATE_SUCCESS'
export const LANGUAGE_UPDATE_FAIL = 'LANGUAGE_UPDATE_FAIL'
export const LANGUAGE_UPDATE_RESET = 'LANGUAGE_UPDATE_RESET'

export const LANGUAGE_DELETE_REQUEST = 'LANGUAGE_DELETE_REQUEST'
export const LANGUAGE_DELETE_SUCCESS = 'LANGUAGE_DELETE_SUCCESS'
export const LANGUAGE_DELETE_FAIL = 'LANGUAGE_DELETE_FAIL'
export const LANGUAGE_DELETE_RESET = 'LANGUAGE_DELETE_RESET'